[package]
name = "json-oracle-encoder"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.86"
ethabi = "18.0.0"
hex = "0.4.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
